import type { Metadata } from "next";
import Navbar from "@/components/navbar"
import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google"
import Footer from "@/components/Footer";
import { Github, Linkedin, Mail, Instagram, Twitter } from 'lucide-react';
import Script from "next/script";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
  (() => {
    const storageKey = "portfolio-theme";
    const storedTheme = localStorage.getItem(storageKey);
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const theme = storedTheme === "light" || storedTheme === "dark"
      ? storedTheme
      : (prefersDark ? "dark" : "light");

    document.documentElement.classList.toggle("dark", theme === "dark");
    document.documentElement.style.colorScheme = theme;
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <body className="antialiased transition-colors duration-300">
        <Script id="theme-init" strategy="beforeInteractive">
          {themeScript}
        </Script>
        <Navbar />
        {children}
        <Footer 
        name="Astitva"
        email="hello@astitva.dev"
        socialLinks={[
          { name: 'GitHub', url: 'https://github.com/yourusername', icon: <Github size={18} /> },
          { name: 'LinkedIn', url: 'https://linkedin.com/in/yourusername', icon: <Linkedin size={18} /> },
          { name: 'Instagram', url: 'https://instagram.com/yourusername', icon: <Instagram size={18} /> },
          { name: 'Twitter', url: 'https://twitter.com/yourusername', icon: <Twitter size={18} /> },
        ]}
      />
      </body>
    </html>
  );
}
