import type { Metadata } from "next";
import Navbar from "@/components/navbar"
import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google"
import Footer from "@/components/Footer";
import { Github, Linkedin, Mail, Instagram, Twitter } from 'lucide-react';


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer 
        name="Astitva"
        email="hello@astitva.dev"
        socialLinks={[
          { name: 'GitHub', url: 'https://github.com/yourusername', icon: <Github size={18} /> },
          { name: 'LinkedIn', url: 'https://linkedin.com/in/yourusername', icon: <Linkedin size={18} /> },
          { name: 'Instagram', url: 'https://instagram.com/yourusername', icon: <Instagram size={18} /> },
          { name: 'Twitter', url: 'https://twitter.com/yourusername', icon: <Twitter size={18} /> },
        ]}
      />
      </body>
    </html>
  );
}